---
alias: guest_mode_on
initial_state: on
trigger:
  - platform: state
    entity_id:
      - input_boolean.guest_mode
    from: 'off'
    to: 'on'
action:
  - service: script.say
    data_template:
      message: >
        {{ [
          "Guest Mode has been enabled for the rest of the day.",
          "Switching to guest mode! ",
          "I have enabled guest mode for the rest of the day. ",
          "System Guest Mode has been enabled. I will minimize the amount of automation for today.",
          "Look but do not touch mode enabled.  Otherwise known as Guest Mode around here.",
          "Guest mode enabled or as I like to call it, Look but do not touch mode.",
          "Awesome! I will take the rest of the day off.  Guest mode has been enabled.",
          "Guest Mode enabled.  In other words, Manual Mode engaged.",
          "Guest mode enabled.  Have Fun!",
          "Family, Friends and Fun.  Guest mode has been enabled today.",
          "Guest Mode enabled.  I am still doing stuff behind the scenes but probably will not turn off the lights on you."
        ] | random }}
